export const USER_ACTION_TYPES = {
  /*
   * USER SESSION
   */
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",

  /*
   * USER SIGN UP
   */
  USER_SIGN_UP_START: "user/USER_SIGN_UP_START",
  USER_SIGN_UP_SUCCESS: "user/USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAILED: "user/USER_SIGN_UP_FAILED",

  /*
   * USER SIGN IN THROUGH EMAIL AND GOOGLE
   */
  GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "user/EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "user/SIGN_IN_FAILED",

  /*
   * USER SIGN OUT
   */
  SIGN_OUT_START: "user/SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "user/SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED: "user/SIGN_OUT_FAILED",
};
